server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://10.253.46.159:3306/zabbix?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: kingstar
    password: kingstar

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #这里是在eureka界面Status栏的显示
    instance-id: payment8001
    #访问路径可以显示ip
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yikai.springcloud.entities

